### ISSUE TITLE
New Project Wizard > File Creation from ini file limits to 8 files?

### ISSUE THREAD

**Issue by blue-devil** [mrfearless/RadASM2#12]
I am now creating ini files for MSYS2(MINGW32 and MINGW64). 

In `Project Wizard - Files & Folders` there are 2 groupboxes: `File Creation` and `Folder Creation`. Those checkboxes are being created in runtime by reading related ini file. 

You cannot add checkboxes more than 8! But I want one more! 

I am going to make if we can add at most 12 checkboxes for both groupboxes?

A quick search direct me:
https://github.com/mrfearless/RadASM2/blob/21301869fa8fd68fd6fa0ed91dc5bb0fed4d0a3c/Addins/CreateProject/Dlg.Asm#L144

@mrfearless  I am going to look for this, any suggestions?

**Comment by mrfearless** [comment]
I would add a third groupbox if needed for additional file/folder creation as existing templates can then still be used with additional missing entries treated as 0

As this is an example of a current template:
```
[MakeDef]
Menu=1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0
```
By adding to the end, and not extending the groups, the older templates will still be usable. So 'newer' templates can make full use of the new checkboxes and thus we wont have to deal with older templates not working. 

Example of newer template using the additional for example 4 extra checkboxes, with 2 new ones selected:

```
[MakeDef]
Menu=1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,0,1,0
```

**Comment by blue-devil** [comment]
My quick search is totally mislead me :/ The problem is not about an addin.

I have solved the problem, in short words,
While creating a project, the project wizards 3rd page has static checkboxes and they are 8 for files and 8 for folders. I added new checkboxes to the resource and then fixed the wizard.asm file. Now it is working like a charm.

I'll work on this in the weekend and when i commit to my fork i'll inform you

Have a nice weekend!

**Comment by mrfearless** [comment]
Ok sound good, thanks, enjoy your weekend as well :D

**Comment by blue-devil** [comment]
I've sent a pull request! If everything is OK we can close this issue =)

**Comment by blue-devil** [comment]
I have tested again, the sources are compiling and the binary is running without problem. #Closing the issue.
