### ISSUE TITLE
Language files are broken

### ISSUE THREAD

**Issue by blue-devil** [mrfearless/RadASM2#14]
Are language files under directory `Language\RadXXX.lang` are broken; or am i missing something?

Those might be plain txt files with UNICODE without BOM; am i right?

Maybe github itself broke those files like it did on lib files in UASMSDK repo?

**Comment by mrfearless** [comment]
Yes plain text files they should be, for example `RadENG.lng`

```
;--------------------------------------------------------------------------------
[Lang]
Lang=English (Default)
;--------------------------------------------------------------------------------
[102]
102=Find..
1012=&Find what:
1009=&Replace:
1003=&Match Case
1004=&Whole Word
1014=&Ignore Whitespace
1005=&Project
```

**Comment by blue-devil** [comment]
* Normally every line should end with `00 0D 00 0A 00`, but broken lng file's lines end with `00 0D 00 0D 0A 00`
* So -I don't know the reason- somehow every line has an extra `0x0D` byte
* Deleting that bytes did not solve the problem, because there is an extra Character encoding problem.
* Notepad++ takes character encoding as ANSI but it should be UNICODE, and converting UNICODE still did not solve the problem.
* I have downloaded Language.zip and FullPackage.zip. LNG files are OK in those zip packages.

Final words; like the lib files I think Github broke the files maybe we consider adding a git attibutes file?

**Comment by blue-devil** [comment]
I want to fix this problem and while playing in my gitlab repo i got this warning:
```
git add *
warning: in the working copy of 'Language/RadCAT.lng', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Language/RadCHN.lng', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Language/RadCHS.lng', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Language/RadENG.lng', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Language/RadESP.lng', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Language/RadFRA.lng', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Language/RadGER.lng', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Language/RadGRE.lng', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Language/RadHEB.lng', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Language/RadITA.lng', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Language/RadKOR.lng', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Language/RadNOR.lng', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Language/RadPt_Br.lng', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Language/RadRUS.lng', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Language/RadTR.lng', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Language/RadUA.lng', LF will be replaced by CRLF the next time Git touches it
```

BTW i commit working lng files to my gitlab repo  and it seems everything is ok, Even though i cannot read them through web browser. But i can open them with notepad after downloading(as a single file). Guess what happened then: I cloned the repo and all the files are are broken again :/ If you download repo as zip file lng files are again broken!

## FINALLY FIXED:
We must mention `*.lng` files as binary in the gitattributes file so git won't touch them!

**Comment by mrfearless** [comment]
Yes, adding `binary` to `*.lng` - I thought that as well, we will take your `.gitattributes` file
