### ISSUE TITLE
NASM compilation error

### ISSUE THREAD

**Issue by JohnKServices** [mrfearless/RadASM2#8]
So when I open an example project (or make any project) and try and run it I get the error 
```
Executing:
"C:\Users\Lucas\Downloads\RadASM-2.2.2.3-FullPackage\Nasm\Projects\WinDlg\WinDlg.exe"
00000002

Make error(s) occured.
Total compile time 1953 ms
```
And it doesn't compile, I have no idea how to post the full error so if you know a way to do that please tell me so I can post it (Also sorry for the bad title, can't think of a better one)

**Comment by mrfearless** [comment]
Hi, I had a quick look at that demo project.

I think the nasm setup and projects was when nasmw was out (and nasm-x), and it used those/expected those files. 

The newer nasm from what i can see is a much different thing. Im not familiar with nasm at all tbh and dont know the ins and outs of the differences, but I think they are significant enough to be mainly incompatible with the current nasm project setup in RadASM - unless someone with a lot of newer nasm knowledge knows and can adjust the files and suggest how resources are compiled, how linking is done, and how to include include files and libraries for common win32 api's.

**Comment by mrfearless** [comment]
Closing this for now. If anyone has experience using newer nasm and wants to advise what tools and settings it should use for RadASM and its example projects, I can always add in that support later on.
